### ISSUE TITLE
ROS 2移行の作業

### ISSUE THREAD

**Issue by uhobeike** [CIT-Autonomous-Robot-Lab/emcl2_ros2#2]
### 作業の予定・基本的なこと
* 5月31日まで（動作確認、[シミュレータ（Raspicat）](https://github.com/rt-net/raspicat_sim/tree/ros2)）
* 作業報告は基本的にここでやる
* **自分の作業の時はアサインをする**
  * **作業たびにマイルストーンを設定する（日付をしっかり設定する）** （どのくらいで作業が終わるか誰でもみれるように）
    * 終わったらマイルストーンを削除（残ったままになるので） 
* わからないことがあったら、ここで聞く
* 次の人に仕事を任せる時は、メンションをして任せる
* ある程度作業が済んだら、作業報告をここでする（リンクとかペタペタすると良いときもある）
* Buildができる状態でマージをする
  * CIが成功するまでマージしてはだめ 
### 作業の流れ
* 以下を元に移行作業を進めていく
https://github.com/CIT-Autonomous-Robot-Lab/emcl2_ros_part
  * **動作確認が完了したらmainにマージする**
  * **porting/ros2-humbleが開発のブランチ** （間違ってmainにマージ＆PRしないように）
    * そこから各々がチェックアウトしてプルリクエストを投げて`Squash and merge`をする
    * プルリクエストの単位は大きすぎないように、ある作業ごとにやると良い

### 作業での注意
* 適当に`git push -f`を使用しない（消し飛ばします（ディアボロ））
  * どうしても使用したい場合は、`--force-with-lease`を使用しましょう 
* フォーマットをしっかりかける（.clang-formatのファイルをパッケージに置くので、それ使ってフォーマット）
* 余計なファイルはpushしない
* コミットする前に`git status`や`git diff`で確認

### コミットやプルリクエストのルール
* コミットについて
  * 最初は大文字 
  * コミットは作業単位で（同じ修正内容だったらファイルをまとめてコミットするのはあり）
  * Fixだけとかはだめ
    * Fix hoge hogeという感じでやったことをしっかり書く 
* プルリクエストについて
  * ブランチの名前は`fix/hoge-hoge`や`feature/super-unti`や`update/untiunti`にする 
  * 基本 `Squash and merge`のみ
  * マージする前に@uhobeikeにチェックの依頼をする

**Comment by uhobeike** [comment]
以下のPRにて
ディレクトリ・ファイル構成・ブランチ周りの
修正を行いました
#3, #4

**Comment by uhobeike** [comment]
てすと

**Comment by uhobeike** [comment]
以下のPRにて
* ディレクトリ・ファイル構成・ブランチ周りの修正を行いました
#3, #4

**Comment by uhobeike** [comment]
以下のPRにて
* clang-formatのContinuationIndentWidthを修正し、インデント幅を4つのスペースにした
#5

**Comment by makotoyoshigoe** [comment]
以下のPRにて
- CMakeLists.txtとpackage.xmlを修正し、```colcon build```が通るようにした
- .github/workflows/test.ymlを修正し、CIが通るようにした
 #6

**Comment by uhobeike** [comment]
.clang-formatの設定を修正
4つのスペースでインデント
* https://github.com/CIT-Autonomous-Robot-Lab/emcl2_ros2/commit/e66ed8533e4d30f6fae06032de257da8eaf967ef

**Comment by uhobeike** [comment]
.clang-formatの設定を修正
タブ幅8が正解だと思われる

* https://github.com/CIT-Autonomous-Robot-Lab/emcl2_ros2/commit/2449c43a1c03a30efd7fcb6c31fce61a33803d93

**Comment by makotoyoshigoe** [comment]
以下のPRにて
- src/emcl2_node.cppとinclude/emcl2/emcl2_node.hを修正し、ROS 2のクラスを作成
- CMakeLists.txtを修正し、ビルド時にsrc/emcl2_node.cppを使用するように変更
 #7

**Comment by uhobeike** [comment]
以下のPRにて
* backword_rosを追加（デバッグ用）
#8

**Comment by Kenzo-Fujisaki** [comment]
emcl2_node.h内の/* came from amclでコメントアウトされているコードはどういった意味ですか？ 
[プログラムのリンク](https://github.com/CIT-Autonomous-Robot-Lab/emcl2_ros2/blob/772c3bbb9696b363316901c8165f578bafaa1ee7/include/emcl2_ros2/emcl2_node.hpp#L39)

**Comment by uhobeike** [comment]
コメントの通り、amclから持ってきたコ－ドという意味です
それをしっかり書き換える予定ですが、(ライセンス的に)現在は移行が優先なのでコメントアウトを外す必要があります

**Comment by Kenzo-Fujisaki** [comment]
分かりました。この部分も移行します。

**Comment by Kenzo-Fujisaki** [comment]
@uhobeike `emcl2_node.cpp`,`emcl2_node.h`の移行で質問があります。
現在パブサブの部分の移行が完了しマージをしてくださいと言われたのですが、サービスやパラメータの移行はまた別のブランチを切りプルリクを出す形になりますか？

**Comment by uhobeike** [comment]
そうですね
となると今のPRのブランチ名を変えないとですね
PRを閉じずに名前変えられますかね？

**Comment by Kenzo-Fujisaki** [comment]
このやり方で大丈夫でしょうか？（チーム開発において危ない作業だと怖いので）

https://docs.github.com/ja/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/renaming-a-branch

**Comment by uhobeike** [comment]
ありがとうございます
そちらの方法で、emcl2_nodeのpublisherとsubscription(pub、subでも良い)の移行をしたというブランチ名に変更して頂けると🙏

**Comment by Kenzo-Fujisaki** [comment]
以下のPRにて

- src/emcl2_node.cppとinclude/emcl2/emcl2_node.hを修正し、パブリッシャとサブスクライバの箇所をROS 2に移行
 https://github.com/CIT-Autonomous-Robot-Lab/emcl2_ros2/pull/11

**Comment by AtsukiUsui** [comment]
以下のファイルををROS 2に移行

- LikelihoodFieldMap.h
- LikelihoodFieldMap.cpp
 #12

**Comment by AtsukiUsui** [comment]
以下のファイルをROS 2に移行

- OdomModel.cpp
 #14

**Comment by AtsukiUsui** [comment]
@uhobeike 質問です
buildをしたら以下のようなエラーがでたのですが、
どのように対応すればよいでしょうか。
```
Starting >>> emcl2   
--- stderr: emcl2                             
/usr/bin/ld: CMakeFiles/emcl2_node.dir/src/Particle.cpp.o:(.bss+0x80000): multiple definition of `emcl2::Mcl::cos_'; CMakeFiles/emcl2_node.dir/src/Mcl.cpp.o:(.bss+0x80000): first defined here
/usr/bin/ld: CMakeFiles/emcl2_node.dir/src/Particle.cpp.o:(.bss+0x0): multiple definition of `emcl2::Mcl::sin_'; CMakeFiles/emcl2_node.dir/src/Mcl.cpp.o:(.bss+0x0): first defined here
collect2: error: ld returned 1 exit status
gmake[2]: *** [CMakeFiles/emcl2_node.dir/build.make:311: emcl2_node] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:137: CMakeFiles/emcl2_node.dir/all] Error 2
gmake: *** [Makefile:146: all] Error 2
---
Failed   <<< emcl2 [2.40s, exited with code 2]
```

**Comment by uhobeike** [comment]
@AtsukiUsui ここを切り取ります。
https://github.com/CIT-Autonomous-Robot-Lab/emcl2_ros2/blob/5429f2e8790d8c385cb98a0e0d4594bba008a2f1/include/emcl2/Mcl.h#L62-L63
切り取ったものを
https://github.com/CIT-Autonomous-Robot-Lab/emcl2_ros2/blob/5429f2e8790d8c385cb98a0e0d4594bba008a2f1/src/Mcl.cpp#L270
に持ってきます。
以上でビルドが通ると思います。
> @uhobeike 質問です buildをしたら以下のようなエラーがでたのですが、 どのように対応すればよいでしょうか。
> 
> ```
> Starting >>> emcl2   
> --- stderr: emcl2                             
> /usr/bin/ld: CMakeFiles/emcl2_node.dir/src/Particle.cpp.o:(.bss+0x80000): multiple definition of `emcl2::Mcl::cos_'; CMakeFiles/emcl2_node.dir/src/Mcl.cpp.o:(.bss+0x80000): first defined here
> /usr/bin/ld: CMakeFiles/emcl2_node.dir/src/Particle.cpp.o:(.bss+0x0): multiple definition of `emcl2::Mcl::sin_'; CMakeFiles/emcl2_node.dir/src/Mcl.cpp.o:(.bss+0x0): first defined here
> collect2: error: ld returned 1 exit status
> gmake[2]: *** [CMakeFiles/emcl2_node.dir/build.make:311: emcl2_node] Error 1
> gmake[1]: *** [CMakeFiles/Makefile2:137: CMakeFiles/emcl2_node.dir/all] Error 2
> gmake: *** [Makefile:146: all] Error 2
> ---
> Failed   <<< emcl2 [2.40s, exited with code 2]
> ```

**Comment by AtsukiUsui** [comment]
以下のファイルをROS 2に移行

- Mcl.h
- Mcl.cpp 
 #15

**Comment by AtsukiUsui** [comment]
以下のファイルをROS 2に移行

- ExpResetMcl.cpp
- ExpResetMcl.h
 #16

**Comment by ShimonShoji** [comment]
以下のファイルのパラメータ部分をROS2に移行
- emcl2_node.cpp
- emcl2_node.h

また、emcl2.param.yamlにパラメータの記述を追加
- emcl2.param.yaml
https://github.com/CIT-Autonomous-Robot-Lab/emcl2_ros2/pull/13

**Comment by ShimonShoji** [comment]
@Kenzo-Fujisaki にemcl2_node.cppとemcl2_node.hの移行作業を受け渡します。
よろしくお願いします🙏

**Comment by AtsukiUsui** [comment]
以下のファイルをROS 2移行

- ExpResetMcl2.cpp
- ExpResetMcl2.h
 #17

**Comment by uhobeike** [comment]
@Kenzo-Fujisaki サービスの移行作業お願いします
> @Kenzo-Fujisaki にemcl2_node.cppとemcl2_node.hの移行作業を受け渡します。 よろしくお願いしますpray

**Comment by Kenzo-Fujisaki** [comment]
@uhobeike Navigation 2では"static_map"がないのですが、どのように対処すればいいでしょうか？

https://github.com/CIT-Autonomous-Robot-Lab/emcl2_ros2/blob/aff4771b09c146f125413cdcfbc6aa527a6225b5/src/emcl2_node.cpp#L104

**Comment by uhobeike** [comment]
なるほど。
そこは、とりあえずサービスではなくて
サブスクライバーでの実装にしましょうか。

こんな感じに
https://github.com/uhobeike/mcl2/blob/acc4303d0b7daa01f299264ed80db7fbd33b9266/src/mcl2_node.cpp#L70

**Comment by Kenzo-Fujisaki** [comment]
サブスクライバでの実装なので、関数[`std::shared_ptr<LikelihoodFieldMap> EMcl2Node::initMap(void)`](https://github.com/CIT-Autonomous-Robot-Lab/emcl2_ros2/blob/6a756f29bb29877cfc816665b11241b5453f7d94/src/emcl2_node.cpp#L119)内での実装ではなく[ここでのやり方のように](https://github.com/uhobeike/mcl2/blob/acc4303d0b7daa01f299264ed80db7fbd33b9266/src/mcl2_node.cpp#L70)新しくサブスクライバとコールバック関数を作成する認識で合っていますか？

**Comment by uhobeike** [comment]
そうです。

**Comment by uhobeike** [comment]
サブスクライバで登録されたコールバック関数の引数は
`hoge::ConstSharedPtr`より`const hoge::ConstSharedPtr`の方が良いので
それ用のPRを作成する予定です。

**Comment by Kenzo-Fujisaki** [comment]
@uhobeike https://github.com/CIT-Autonomous-Robot-Lab/emcl2_ros2/pull/18#pullrequestreview-1425876065 を受け考え、[`#include "nav_msgs/srv/get_map.hpp"`](https://github.com/CIT-Autonomous-Robot-Lab/emcl2_ros2/blob/6a756f29bb29877cfc816665b11241b5453f7d94/src/emcl2_node.cpp#L11)の削除のみ分かりましたが、他にもありますでしょうか？

**Comment by uhobeike** [comment]
そこだけだと思われます
> @uhobeike [#18 (review)](https://github.com/CIT-Autonomous-Robot-Lab/emcl2_ros2/pull/18#pullrequestreview-1425876065) を受け考え、[`#include "nav_msgs/srv/get_map.hpp"`](https://github.com/CIT-Autonomous-Robot-Lab/emcl2_ros2/blob/6a756f29bb29877cfc816665b11241b5453f7d94/src/emcl2_node.cpp#L11)の削除のみ分かりましたが、他にもありますでしょうか？

**Comment by Kenzo-Fujisaki** [comment]
@uhobeike 次の引き継ぎは[タイマーの部分](https://github.com/CIT-Autonomous-Robot-Lab/emcl2_ros2/blob/c44ecdf4b0c963d35e16a2c6b5dc2aafcf9a2d44/include/emcl2/emcl2_node.h#LL55C2-L55C32)で大丈夫でしょうか？

**Comment by uhobeike** [comment]
@Kenzo-Fujisaki タイマーの部分をどう移行する予定でしょうか？

**Comment by Kenzo-Fujisaki** [comment]
どう移行するかまではまだ考えてないです。

**Comment by uhobeike** [comment]
考えてください。
`このように移行する予定ですが、どうですか？`
まで無いとこちら側としてはOK出せないです。

**Comment by Kenzo-Fujisaki** [comment]
以下のPRにて

- `emcl2.hpp`, `emcl2.cpp`内のサービスの箇所をROS 2に移行
- `package.xml`に`<depend>std_srvs</depend>`を追加
- [`ros::service::call`](https://github.com/CIT-Autonomous-Robot-Lab/emcl2_ros2/blob/c44ecdf4b0c963d35e16a2c6b5dc2aafcf9a2d44/src/emcl2_node.cpp#LL134C1-L134C1)の箇所をサブスクライバとして実装
https://github.com/CIT-Autonomous-Robot-Lab/emcl2_ros2/pull/18

**Comment by Kenzo-Fujisaki** [comment]
@uhobeike [`ros::Time scan_time_stamp_`](https://github.com/CIT-Autonomous-Robot-Lab/emcl2_ros2/blob/c44ecdf4b0c963d35e16a2c6b5dc2aafcf9a2d44/include/emcl2/emcl2_node.h#L55)と関連する箇所のROS 2移行はどうでしょうか？

**Comment by uhobeike** [comment]
なぜそこだけですか？
そこだけ移行するメリットはありますか？
先のことを考えてください。

**Comment by Kenzo-Fujisaki** [comment]
@uhobeike すいません。少し混乱気味なので整理がしたいです。
今担当している箇所[`emcl2_node.cpp、emcl2_node.hpp（パラメータの部分、メッセージの部分）`](https://github.com/CIT-Autonomous-Robot-Lab/emcl2_ros_part#%E5%BD%B9%E5%89%B2%E5%88%86%E6%8B%85)はどこがゴールでしょうか？
[tf2](https://github.com/CIT-Autonomous-Robot-Lab/emcl2_ros2/blob/c44ecdf4b0c963d35e16a2c6b5dc2aafcf9a2d44/include/emcl2/emcl2_node.h#LL14C1-L18C3)は除外だと思っていますが、[タイマー部分関連](https://github.com/CIT-Autonomous-Robot-Lab/emcl2_ros2/blob/c44ecdf4b0c963d35e16a2c6b5dc2aafcf9a2d44/include/emcl2/emcl2_node.h#LL55C2-L55C32)は含めるのでしょうか？

**Comment by uhobeike** [comment]
多分もうゴールです。
ここからは、シミュレータを使って移行作業を進めて行きます。
@IkuoShige の担当になってくると思ってます。

**Comment by Kenzo-Fujisaki** [comment]
ありがとうございます。
それを踏まえてもう一度考え直してみます。

**Comment by IkuoShige** [comment]
@uhobeike 手の空いているときに[check/tf-debugブランチ](https://github.com/CIT-Autonomous-Robot-Lab/emcl2_ros2/tree/check/tf-debug)でのデバッグをお願いします。
現状は、emcl2_nodeの関数の移行を行い、tfを使えるようにしましたが、rviz側に自己位置推定の情報が表示されていない状態です。
https://github.com/CIT-Autonomous-Robot-Lab/emcl2_ros2/blob/check/tf-debug/src/emcl2_node.cpp#L407-#L408
気になっているところは、上記の箇所です。本来`rclcpp::Time(0)`ですが、エラーを吐いたため`ros_clock_.now()`に変更したところエラーを吐かなくなりました。
僕も引き続き調査します。

**Comment by uhobeike** [comment]
#21 でとりあえず、自己位置推定が動くようになりました。
ここからは、細かい修正や機能してない部分の修正を行います。
あとは、パッケージの仕上げをしていきます。

**Comment by uhobeike** [comment]
現在確認している問題（コードというより、機能的な問題）
* emcl2の実行周期がプログラム通りでない？もっと早く回る予定であるが、1sで回ってる気がする
* initialposeでセットした位置にパーティクルが来ない
* パラメータでinitialposeをセットできるようにする
* serviceでマップの取得
  * 現在トピック経由で取得（QOSの設定次第で運用可能？）

**Comment by uhobeike** [comment]
#34 お疲れした。
