### ISSUE TITLE
preparation of quick start

### ISSUE THREAD

**Issue by ryuichiueda** [CIT-Autonomous-Robot-Lab/emcl2_ros2#35]
A manual for trying emcl2 in a simulation will be required in README. 

## example

```bash
$ some procedures
$ to install
$ ros2 launch emcl2_ros2 try_emcl2_in_simulator.launch.py 
```

**Comment by ryuichiueda** [comment]
↑I added some command lines.

**Comment by ryuichiueda** [comment]
Try_emcl2_in_simulator.launch.py is not requied if how to prepare a simulated environment is written.

**Comment by uhobeike** [comment]
@ryuichiueda Quick start was prepared in #37.
